api_platform:
    title:       'API symfony demo'
    description: 'API symfony demo description'
    version:     '0.0.0'
    show_webby:  false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
