# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    env(RABBITMQ_VHOST): 'symfony-demo'
    env(RABBITMQ_URL): 'amqp://test:test@localhost:5672'

    rabbitmq_host: '%env(RABBITMQ_HOST)%'
    env(RABBITMQ_HOST): localhost
    rabbitmq_user: '%env(RABBITMQ_USER)%'
    env(RABBITMQ_USER): test
    rabbitmq_password: '%env(RABBITMQ_PASSWORD)%'
    env(RABBITMQ_PASSWORD): test

old_sound_rabbit_mq:
    connections:
        default:
            host:     '%rabbitmq_host%'
            port:     5672
            user:     '%rabbitmq_user%'
            password: '%rabbitmq_password%'
            vhost:    '%env(RABBITMQ_VHOST)%'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

            #requires php_sockets.dll
            use_socket: false # default false
    producers:
        emailing:
            connection:       default
            exchange_options: {name: emails_ex, type: fanout}

        delayed_send_email:
            connection:       default
            exchange_options: { name: 'notification.v1.send_email_delayed', type: direct }
            queue_options:
                name: 'notification.v1.send_email_delayed'
                arguments:
                    x-dead-letter-exchange: ['S', 'notification.v1.send_email']
                    x-message-ttl:          ['I', '100000']
                    x-ha-policy:            ['S', 'all']

    consumers:
        emailing:
            connection:       default
            exchange_options: { name: emails_ex, type: fanout }
            queue_options:
                name: emails_qu
                arguments:
                    x-dead-letter-exchange:    ['S', 'emailing_send_dead_letter_ex']
                    x-dead-letter-routing-key: ['S', 'emailing_send_dead_letter_qu']
                    x-message-ttl:          ['I', '3600000']
                    x-ha-policy:            ['S', 'all']
            callback:         App\Consumer\EmailService

        emailing_send_dead_letter:
            connection:       default
            exchange_options: { name: emailing_send_dead_letter_ex, type: fanout }
            queue_options:    { name: emailing_send_dead_letter_qu }
            callback:         App\Consumer\EmailDeadLetterConsumer
